version: '3'
services:
  ft:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '3001:3000'
      - '9223:9222'
    environment:
      HOST: 0.0.0.0
    volumes:
      - ../:/workspace
      - build:/workspace/build
      - node_modules:/workspace/node_modules
    command: sleep infinity

volumes:
  node_modules:
  build:
